-- DROP ALL TABLES FIRST
DROP TABLE IF EXISTS "OrderItemOption" CASCADE;
DROP TABLE IF EXISTS "OrderItemVariant" CASCADE;
DROP TABLE IF EXISTS "OrderItem" CASCADE;
DROP TABLE IF EXISTS "Order" CASCADE;
DROP TABLE IF EXISTS "MenuOptionValue" CASCADE;
DROP TABLE IF EXISTS "MenuItemOption" CASCADE;
DROP TABLE IF EXISTS "MenuItemVariant" CASCADE;
DROP TABLE IF EXISTS "MenuItem" CASCADE;
DROP TABLE IF EXISTS "MenuCategory" CASCADE;
DROP TABLE IF EXISTS "Table" CASCADE;
DROP TABLE IF EXISTS "User" CASCADE;
DROP TABLE IF EXISTS "Branch" CASCADE;
DROP TABLE IF EXISTS "Restaurant" CASCADE;

-- Now drop the lowercase versions
DROP TABLE IF EXISTS order_item_options CASCADE;
DROP TABLE IF EXISTS order_item_variants CASCADE;
DROP TABLE IF EXISTS order_items CASCADE;
DROP TABLE IF EXISTS orders CASCADE;
DROP TABLE IF EXISTS menu_option_values CASCADE;
DROP TABLE IF EXISTS menu_item_options CASCADE;
DROP TABLE IF EXISTS menu_item_variants CASCADE;
DROP TABLE IF EXISTS menu_items CASCADE;
DROP TABLE IF EXISTS menu_categories CASCADE;
DROP TABLE IF EXISTS tables CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS branches CASCADE;
DROP TABLE IF EXISTS restaurants CASCADE;

SELECT 'All tables dropped. Now run the neon-correct-schema.sql script!' as status;
